import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://127.0.0.1:5173/');
await expect(page.getByRole('button',{name:'เริ่มวิ่งสาธิต',exact:true})).toBeEnabled({timeout:30000});
await page.waitForTimeout(1500);
await page.screenshot({path:'test-results/desktop.png',fullPage:true});
await page.getByRole('button',{name:'ใกล้ตัวรถ',exact:true}).click();
await page.waitForTimeout(1800);
await page.screenshot({path:'test-results/detail.png',fullPage:true});
await page.getByRole('switch',{name:'ไฟ AGV',exact:true}).click();
await expect(page.getByRole('switch',{name:'ไฟ AGV',exact:true})).toHaveAttribute('aria-checked','false');
await page.getByRole('switch',{name:'ไฟโรงงาน',exact:true}).click();
await expect(page.getByText('โหมดแสงสลัว',{exact:true})).toBeVisible();
await page.getByRole('switch',{name:'ไฟ AGV',exact:true}).click();
await page.waitForTimeout(900);
await page.screenshot({path:'test-results/night.png',fullPage:true});
await page.getByRole('button',{name:'1.5×',exact:true}).click();
await page.getByRole('button',{name:'ติดตาม',exact:true}).click();
await page.getByRole('button',{name:'เริ่มวิ่งสาธิต',exact:true}).click();
await expect(page.getByTestId('status')).toHaveText('กำลังเคลื่อนที่');
await page.waitForTimeout(1500);
await page.getByRole('button',{name:'พักการสาธิต',exact:true}).click();
await expect(page.getByTestId('status')).toHaveText('พัก');
await page.getByRole('button',{name:'เล่นต่อ',exact:true}).click();
await expect(page.getByTestId('status')).toHaveText('จอดที่สถานี B',{timeout:90000});
console.log('Reached B');
await expect(page.getByTestId('status')).toHaveText('จอดที่สถานี A',{timeout:90000});
console.log('Completed A -> B -> A');
await page.getByRole('button',{name:'เริ่มต้นใหม่'}).click();
await expect(page.getByTestId('status')).toHaveText('พร้อม');
await expect(page.getByRole('button',{name:'1.0×',exact:true})).toHaveAttribute('aria-pressed','true');
await expect(page.getByRole('switch',{name:'ไฟโรงงาน',exact:true})).toHaveAttribute('aria-checked','true');
await page.getByRole('button',{name:'ขยายฉาก',exact:true}).click();
await expect(page.locator('aside')).toBeHidden();
await page.getByRole('button',{name:'แสดงแผงควบคุม',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(900);
await page.screenshot({path:'test-results/mobile.png',fullPage:true});
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
await page.getByRole('switch',{name:'ไฟ AGV',exact:true}).focus();
await page.keyboard.press('Space');
await expect(page.getByRole('switch',{name:'ไฟ AGV',exact:true})).toHaveAttribute('aria-checked','false');
console.log('Browser errors:',JSON.stringify(errors));
expect(errors).toEqual([]);
await browser.close();
console.log('Desktop, mobile, lights, cameras, playback, full route, reset and keyboard checks passed');
